// <auto-generated />
using System;
using K01Y25_Nhom4_BT02.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace K01Y25_Nhom4_BT02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113032952_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("K01Y25_Nhom4_BT02.DB.Table.Course", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Courseid"));

                    b.Property<double>("Credits")
                        .HasColumnType("double precision")
                        .HasColumnName("credits");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Courseid");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("K01Y25_Nhom4_BT02.DB.Table.Enrollment", b =>
                {
                    b.Property<int>("Enrollmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enrollmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Enrollmentid"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<decimal>("Grade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("grade");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.HasKey("Enrollmentid");

                    b.HasIndex("Courseid");

                    b.HasIndex("Studentid");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("K01Y25_Nhom4_BT02.DB.Table.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Enrollmentdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollmentdate");

                    b.Property<string>("Firstmidname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firstmidname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("K01Y25_Nhom4_BT02.DB.Table.Enrollment", b =>
                {
                    b.HasOne("K01Y25_Nhom4_BT02.DB.Table.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Courseid")
                        .IsRequired()
                        .HasConstraintName("fk_course");

                    b.HasOne("K01Y25_Nhom4_BT02.DB.Table.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("Studentid")
                        .IsRequired()
                        .HasConstraintName("fk_student");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("K01Y25_Nhom4_BT02.DB.Table.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("K01Y25_Nhom4_BT02.DB.Table.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
